import type { Metadata } from "next";

import "@/styles/globals.css";

import GlobalHeader from "@/components/GlobalHeader";

import { cn } from "@/utils/tailwind-merge";
import { plusJakartaSans } from "@/styles/fonts";

import "swiper/css";
import "swiper/css/effect-coverflow";
import "swiper/css/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        {/* Fonts */}
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-dynamic-subset.min.css"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable-jp-dynamic-subset.min.css"
        />
      </head>

      <body className={cn(plusJakartaSans.className, "antialiased")}>
        <GlobalHeader />
        {children}
      </body>
    </html>
  );
}
